# Generated by Django 4.0.6 on 2022-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DNF_Showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DNF_Showcase.c'),
        ),
    ]
